name: godzyken
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.4
  get: ^4.6.1
  get_test: any
  getxfire: 0.3.1
  flutter_web3: 2.1.6
  niku: 1.1.3
  date_format: 2.0.4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.4
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/image/carrelage_background.jpg
    - assets/image/godzy_logo.png
    - assets/image/github_logo.png
    - assets/image/logo_bat_services.png
    - assets/image/digital-transformation-teaser.jpg
    - assets/image/digital_transf.jpg
    - assets/image/maison_indiv.png
    - assets/image/appartement.png
  uses-material-design: true

